In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_customer_feedback.csv
/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_customers.csv
/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_order_items.csv
/kaggle/input/datasets/akxiit/blinkit-sales-dataset/Category_Icons.xlsx
/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_inventory.csv
/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_delivery_performance.csv
/kaggle/input/datasets/akxiit/blinkit-sales-dataset/Rating_Icon.xlsx
/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_inventoryNew.csv
/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_orders.csv
/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_marketing_performance.csv
/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_products.csv

In [2]:
orders = pd.read_csv('/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_orders.csv')
orders

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741
...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,62600289,2023-12-25 15:46:20,2023-12-25 16:05:20,2023-12-25 16:10:20,On Time,1132.33,Cash,90914,1587
4996,8340761903,53640286,2023-11-27 09:18:43,2023-11-27 09:38:43,2023-11-27 09:36:43,On Time,2372.01,Cash,27952,3458
4997,5936301790,87059497,2024-06-21 19:09:09,2024-06-21 19:23:09,2024-06-21 19:26:09,On Time,3158.35,Cash,9590,7424
4998,5710579377,67310893,2024-06-06 14:58:13,2024-06-06 15:12:13,2024-06-06 15:10:13,On Time,1918.92,UPI,29940,6128
4999,2494813730,28663279,2023-08-23 12:04:18,2023-08-23 12:20:18,2023-08-23 12:21:18,On Time,1879.46,Card,32851,5588

In [3]:
order_items = pd.read_csv('/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_order_items.csv')
order_items

        order_id  product_id  quantity  unit_price
0     1961864118      642612         3      517.03
1     1549769649      378676         1      881.42
2     9185164487      741341         2      923.84
3     9644738826      561860         1      874.78
4     5427684290      602241         2      976.55
...          ...         ...       ...         ...
4995  1669690997      925482         3      475.04
4996  8340761903      124290         2       39.65
4997  5936301790      491314         3      973.44
4998  5710579377      319388         2      657.80
4999  2494813730      136533         1      826.21

[5000 rows x 4 columns]

In [4]:

blinkit_orders = pd.read_csv('/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_orders.csv')
blinkit_orders.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

In [5]:
blinkit_inventory = pd.read_csv('/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_inventoryNew.csv')
blinkit_inventory

       product_id    date  stock_received  damaged_stock
0          153019  Mar-23               4              1
1          848226  Mar-23               4              1
2          965755  Mar-23               1              0
3           39154  Mar-23               4              0
4           34186  Mar-23               3              1
...           ...     ...             ...            ...
18100      837480  Nov-24               3              0
18101       56589  Nov-24               3              0
18102      679284  Nov-24               3              0
18103      673058  Nov-24               3              0
18104      114414  Nov-24               3              0

[18105 rows x 4 columns]

In [6]:
blinkit_order_items = pd.read_csv('/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_order_items.csv')
blinkit_order_items

        order_id  product_id  quantity  unit_price
0     1961864118      642612         3      517.03
1     1549769649      378676         1      881.42
2     9185164487      741341         2      923.84
3     9644738826      561860         1      874.78
4     5427684290      602241         2      976.55
...          ...         ...       ...         ...
4995  1669690997      925482         3      475.04
4996  8340761903      124290         2       39.65
4997  5936301790      491314         3      973.44
4998  5710579377      319388         2      657.80
4999  2494813730      136533         1      826.21

[5000 rows x 4 columns]

In [7]:


merge_ords_ordID = pd.merge(orders, order_items, on='order_id', how='outer', indicator=True)

print(" ")
merge_ords_ordID['_merge'].value_counts()

_merge
both          5000
left_only        0
right_only       0
Name: count, dtype: int64

In [8]:
merge_ords_ordID.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,product_id,quantity,unit_price,_merge
0,60465,15808945,2024-10-23 05:23:29,2024-10-23 05:34:29,2024-10-23 05:39:29,On Time,589.47,UPI,58998,3943,361361,2,826.21,both
1,2237858,48281892,2023-04-02 03:45:11,2023-04-02 04:00:11,2023-04-02 04:03:11,On Time,3835.26,Wallet,97945,1987,585299,1,799.46,both
2,3101265,89617089,2024-05-23 03:21:47,2024-05-23 03:37:47,2024-05-23 03:40:47,On Time,3567.73,UPI,20246,974,300159,1,44.35,both
3,5120698,44174426,2023-06-09 12:10:20,2023-06-09 12:25:20,2023-06-09 12:40:20,Slightly Delayed,3064.36,Wallet,48582,3184,187399,1,53.49,both
4,5512907,51476157,2023-04-30 20:52:21,2023-04-30 21:11:21,2023-04-30 21:26:21,Slightly Delayed,861.53,Wallet,44545,419,659290,3,319.34,both

In [9]:
daily_orders_on_product = merge_ords_ordID[['order_id', 'order_date', 'payment_method', 'product_id', 'quantity']]
daily_orders_on_product

        order_id           order_date payment_method  product_id  quantity
0          60465  2024-10-23 05:23:29            UPI      361361         2
1        2237858  2023-04-02 03:45:11         Wallet      585299         1
2        3101265  2024-05-23 03:21:47            UPI      300159         1
3        5120698  2023-06-09 12:10:20         Wallet      187399         1
4        5512907  2023-04-30 20:52:21         Wallet      659290         3
...          ...                  ...            ...         ...       ...
4995  9993542681  2023-05-23 04:12:41            UPI      880510         1
4996  9996182478  2023-04-18 13:13:06            UPI      592784         3
4997  9997121955  2024-04-21 00:03:15            UPI      739534         2
4998  9997994965  2023-12-27 14:02:18           Card      461804         2
4999  9998297778  2023-09-22 17:07:28           Card      709916         3

[5000 rows x 5 columns]

In [10]:
daily_orders_on_product['order_date'].dtype

dtype('O')

In [11]:
products_daily = daily_orders_on_product[['order_date', 'product_id','quantity']]
products_daily

               order_date  product_id  quantity
0     2024-10-23 05:23:29      361361         2
1     2023-04-02 03:45:11      585299         1
2     2024-05-23 03:21:47      300159         1
3     2023-06-09 12:10:20      187399         1
4     2023-04-30 20:52:21      659290         3
...                   ...         ...       ...
4995  2023-05-23 04:12:41      880510         1
4996  2023-04-18 13:13:06      592784         3
4997  2024-04-21 00:03:15      739534         2
4998  2023-12-27 14:02:18      461804         2
4999  2023-09-22 17:07:28      709916         3

[5000 rows x 3 columns]

In [12]:
products_daily['product_id'].unique().size

268

In [13]:
merge_ords_ordID['order_date'] = pd.to_datetime(merge_ords_ordID['order_date'])

In [14]:
merge_ords_ordID['order_date'] = pd.to_datetime(
    merge_ords_ordID['order_date']
).dt.normalize()

In [15]:
grouped = merge_ords_ordID.groupby(['order_date', 'product_id'])

daily_product_sales = grouped['quantity'].sum().reset_index()
daily_product_sales

     order_date  product_id  quantity
0    2023-03-16        9436         2
1    2023-03-16       14145         3
2    2023-03-16      136533         1
3    2023-03-16      240179         1
4    2023-03-16      272170         1
...         ...         ...       ...
4915 2024-11-03      992178         3
4916 2024-11-04      131136         2
4917 2024-11-04      435929         3
4918 2024-11-04      667163         2
4919 2024-11-04      871592         1

[4920 rows x 3 columns]

In [16]:
daily_product_sales['order_date'].unique().size

600

In [17]:
daily_product_sales['order_date'].unique()

<DatetimeArray>
['2023-03-16 00:00:00', '2023-03-17 00:00:00', '2023-03-18 00:00:00',
 '2023-03-19 00:00:00', '2023-03-20 00:00:00', '2023-03-21 00:00:00',
 '2023-03-22 00:00:00', '2023-03-23 00:00:00', '2023-03-24 00:00:00',
 '2023-03-25 00:00:00',
 ...
 '2024-10-26 00:00:00', '2024-10-27 00:00:00', '2024-10-28 00:00:00',
 '2024-10-29 00:00:00', '2024-10-30 00:00:00', '2024-10-31 00:00:00',
 '2024-11-01 00:00:00', '2024-11-02 00:00:00', '2024-11-03 00:00:00',
 '2024-11-04 00:00:00']
Length: 600, dtype: datetime64[ns]

In [18]:
full_dates = pd.date_range(daily_product_sales['order_date'].min(), daily_product_sales['order_date'].max())
full_dates

DatetimeIndex(['2023-03-16', '2023-03-17', '2023-03-18', '2023-03-19',
               '2023-03-20', '2023-03-21', '2023-03-22', '2023-03-23',
               '2023-03-24', '2023-03-25',
               ...
               '2024-10-26', '2024-10-27', '2024-10-28', '2024-10-29',
               '2024-10-30', '2024-10-31', '2024-11-01', '2024-11-02',
               '2024-11-03', '2024-11-04'],
              dtype='datetime64[ns]', length=600, freq='D')

In [19]:
products = daily_product_sales['product_id'].unique()

full_index = daily_product_sales['product_id'].unique()

full_index = pd.MultiIndex.from_product(
    [products,full_dates],
    names=['product_id','date']
)

In [20]:
full_index

MultiIndex([(  9436, '2023-03-16'),
            (  9436, '2023-03-17'),
            (  9436, '2023-03-18'),
            (  9436, '2023-03-19'),
            (  9436, '2023-03-20'),
            (  9436, '2023-03-21'),
            (  9436, '2023-03-22'),
            (  9436, '2023-03-23'),
            (  9436, '2023-03-24'),
            (  9436, '2023-03-25'),
            ...
            (753354, '2024-10-26'),
            (753354, '2024-10-27'),
            (753354, '2024-10-28'),
            (753354, '2024-10-29'),
            (753354, '2024-10-30'),
            (753354, '2024-10-31'),
            (753354, '2024-11-01'),
            (753354, '2024-11-02'),
            (753354, '2024-11-03'),
            (753354, '2024-11-04')],
           names=['product_id', 'date'], length=160800)

In [21]:
full_df = pd.DataFrame(index=full_index).reset_index()

In [26]:
full_df.rename(columns={'date': 'order_date'}, inplace=True)

In [27]:
full_df

        product_id order_date
0             9436 2023-03-16
1             9436 2023-03-17
2             9436 2023-03-18
3             9436 2023-03-19
4             9436 2023-03-20
...            ...        ...
160795      753354 2024-10-31
160796      753354 2024-11-01
160797      753354 2024-11-02
160798      753354 2024-11-03
160799      753354 2024-11-04

[160800 rows x 2 columns]

In [30]:
df_full = full_df.merge(daily_product_sales,
                       on =['product_id','order_date'],
                       how='left'
                       )
df_full

        product_id order_date  quantity
0             9436 2023-03-16       2.0
1             9436 2023-03-17       NaN
2             9436 2023-03-18       NaN
3             9436 2023-03-19       NaN
4             9436 2023-03-20       NaN
...            ...        ...       ...
160795      753354 2024-10-31       NaN
160796      753354 2024-11-01       NaN
160797      753354 2024-11-02       NaN
160798      753354 2024-11-03       NaN
160799      753354 2024-11-04       NaN

[160800 rows x 3 columns]

In [32]:
df_full[df_full['quantity'].isna()]

        product_id order_date  quantity
1             9436 2023-03-17       NaN
2             9436 2023-03-18       NaN
3             9436 2023-03-19       NaN
4             9436 2023-03-20       NaN
5             9436 2023-03-21       NaN
...            ...        ...       ...
160795      753354 2024-10-31       NaN
160796      753354 2024-11-01       NaN
160797      753354 2024-11-02       NaN
160798      753354 2024-11-03       NaN
160799      753354 2024-11-04       NaN

[155880 rows x 3 columns]

In [33]:
df_full['quantity'] = df_full['quantity'].fillna(0)

df_full.isna().sum()

product_id    0
order_date    0
quantity      0
dtype: int64

In [34]:
df_full = df_full.rename(columns={'order_date':'date'})

In [35]:
df_full.head()

   product_id       date  quantity
0        9436 2023-03-16       2.0
1        9436 2023-03-17       0.0
2        9436 2023-03-18       0.0
3        9436 2023-03-19       0.0
4        9436 2023-03-20       0.0

In [36]:
df_full = df_full.sort_values(['product_id','date'])

# **Top products**

In [41]:
product_sales = df_full.groupby('product_id')['quantity'].sum()

In [42]:
product_sales.describe()

count    268.000000
mean      37.440299
std        9.177004
min        9.000000
25%       31.000000
50%       37.000000
75%       43.000000
max       70.000000
Name: quantity, dtype: float64

In [47]:
product_sales

product_id
4452      39.0
6405      34.0
9436      44.0
11422     27.0
14145     40.0
          ...
970529    45.0
990993    37.0
991434    44.0
992178    60.0
993331    23.0
Name: quantity, Length: 268, dtype: float64

In [48]:
#top 50 products

top_products = product_sales.sort_values(ascending=False).head(50).index
df_model = df_full[df_full['product_id'].isin(top_products)]

In [49]:
(product_sales > 200).sum()

np.int64(0)

In [44]:
blinkit_products = pd.read_csv('/kaggle/input/datasets/akxiit/blinkit-sales-dataset/blinkit_products.csv')
blinkit_products

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55
...,...,...,...,...,...,...,...,...,...,...
263,444361,Pain Reliever,Pharmacy,"Prakash, Bawa and Kale",822.63,1028.29,20.0,365,20,71
264,679284,Cough Syrup,Pharmacy,Pant LLC,877.89,1097.36,20.0,365,28,95
265,240179,Cough Syrup,Pharmacy,Ram-Suri,90.56,113.20,20.0,365,20,56
266,673058,Cough Syrup,Pharmacy,Balan-Madan,765.76,957.20,20.0,365,30,94
267,114414,Vitamins,Pharmacy,Kara-Golla,832.06,1040.07,20.0,365,26,66

# *weekly data***

In [50]:
df_full['week'] = df_full['date'].dt.to_period('W')